config/routes.rb
Rails.application.routes.draw do
  get "/", to: "static#index", as: "root"

  get "register", to: "users#new", as: "new_user"
  post "register", to: "users#create"

  get "login", to: "sessions#index", as: "login"
  post "login", to: "sessions#login"
  get "logout", to: "sessions#logout"

  get "items", to: "items#index", as: "items"
  get "items/:id", to: "items#show", as: "item"
  post "items/:id/add_to_cart", to: "items#add_to_cart", as: "add_to_cart"
  delete "items/:id/remove_from_cart", to: "items#remove_from_cart", as: "remove_item_from_cart"
  post "items/:id/add_to_build", to: "items#add_to_build", as: "add_to_build"
  post "items/:build_id", to: "items#add_build_to_cart", as: "add_build_to_cart"
  post "items", to: "items#post"

  get "cart", to: "carts#show", as: "cart"
  post "cart/clear", to: "carts#delete", as: "clear_cart"

  get "users/:id/", to: "builds#private_index", as: "user"

  get "builds", to: "builds#index", as: "builds"

  get "users/:id/:build_id", to: "builds#show", as: "build"
  get "builds/new", to: "builds#new", as: "new_build"
  get "builds/:build_id/edit", to: "builds#edit", as: "edit_build"
  delete "builds/:build_id/:item_id", to: "builds#remove_item", as: "delete_item_from_build"

  patch "builds/:build_id", to: "builds#update", as: "update_build"
  post "builds", to: "builds#create"
  post "users/:id/:build_id", to: "builds#post"
  delete "users/:id/:build_id", to: "builds#delete"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/build.rb
class Build < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true

  has_many :builds_items
  has_many :items, through: :builds_items

  belongs_to :user

  def publish
    self.public = true
    self.save
  end

  def unpublish
    self.public = false
    self.save
  end
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  def index
    @colors = colors
    @builds = Build.where(public: true).shuffle
  end

  def private_index
    @colors = colors
    @user = User.find(params[:id])
    @builds = Build.where(user_id: @user.id).shuffle
  end

  def show
    @build = Build.find(params[:build_id])
    @owner = User.find(@build.user_id)
    @user = user

    @items = @build.items

    @item = Item.find(params[:it]) rescue Item.new
    @user_builds = user.builds
  end

  def edit
    @build = Build.find(params[:build_id])
    if (session[:user] != @build.user_id)
      redirect_to root_path
    end
  end

  def post
    @build = Build.find(params[:build_id])
    if @build.public
      @build.unpublish
    else
      @build.publish
    end

    redirect_to build_path(@build.user, @build)
  end

  def create
    @build = Build.new(build_params)
    @build.user_id = user.id
    if @build.save
      redirect_to build_path(user, @build)
    else
      flash.now[:message] = @build.errors.full_messages[0]
      render new
    end
  end

  def update
    @build = Build.find(params[:build_id])

    if @build.update(build_params)
      redirect_to build_path(user, @build)
    else
      flash.now[:message] = @build.errors.full_messages[0]
      render new
    end
  end

  def delete
    build = Build.find(params[:build_id])
    build.destroy
    redirect_to user_path(user)
  end

  def remove_item
    item = params[:item_id]
    build = params[:build_id]
    build_item = BuildsItem.where(item_id: item).where(build_id: build).first
    build_item.destroy
    redirect_to build_path(user, build)
  end

  private

  def colors
    ["#ef5350", "#ec407a", "#ab47bc", "#7e57c2", "#5c6bc0", "#42a5f5", "#29b6f6", "#26c6da",
     "#26a69a", "#66bb6a", "#9ccc65", "#d4e157", "#ffee58", "#ffca28", "#ffa726", "#ff7043",
     "#8d6e63", "#78909c"]
  end

  def build_params
    params.require(:build).permit(:title, :description, :id, :user_id)
  end
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/views/builds/edit.html.erb
<div class="new-build-wrapper">
  <img  class="build-image" src="https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fdch81km8r5tow.cloudfront.net%2Fwp-content%2Fuploads%2F2017%2F07%2FFA17_Skate_UltraRangePro_LS_11.jpg&f=1&nofb=1"/>
  <div class="login-form build-form">
    <h3 class="build-form-title">Edit Build</h3>
    <form action="/builds/<%=@build.id%>" accept-charset="UTF-8" method="post">
      <input type="hidden" name="_method" value="patch">
      <input type="hidden" name="authenticity_token" value="MLgPou1mJV4GiB+DSV21cf7NSm9UQ14M7GrrssBoD0A3/ri9BkbJGWWeAkT473CtaJTUA1vFIIK4YiKlcXRKyQ==">
      <div class="form-label-group">
        <input type="text" name="build[title]" id="inputText" value="<%=@build.title%>" class="form-control" placeholder="Title" required autofocus>
      </div>
      <div class="form-label-group">
        <textarea type="textarea" name="build[description]" value=<%=@build.description%> id="inputPassword" class="form-control" placeholder="Description" rows="4'" style="resize:none;" required></textarea>
      </div>
      <button class="item-content-btn" type="submit">Edit</button>
    </form>
  </div>
</div>

app/views/builds/index.html.erb
<div class= "builds-wrapper">
  <h1>Public Builds</h1>
  <div class="builds-content">
    <% @builds.each do |build|%>
      <a class="builds-card" style="background: <%=@colors.sample%>" href=<%=build_path(build.user,build)%>>
        <div class="builds-div"></div>
        <div class="builds-content">
          <%= content_tag(:span, build.title, class:"builds-title") %>
          <%= content_tag(:span, build.description,class:"builds-description") %>
          <%= content_tag(:span, build.user.name, class:"builds-author")%>
        </div>
      </a>
    <%end%>
  </div>
</div>

app/views/builds/new.html.erb
<div class="new-build-wrapper">
  <img  class="build-image" src="https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fdch81km8r5tow.cloudfront.net%2Fwp-content%2Fuploads%2F2017%2F07%2FFA17_Skate_UltraRangePro_LS_11.jpg&f=1&nofb=1"/>
  <div class="login-form build-form">
    <h3 class="build-form-title">Create Build</h3>
    <form action="/builds" accept-charset="UTF-8" method="post">
      <input type="hidden" name="authenticity_token" value="MLgPou1mJV4GiB+DSV21cf7NSm9UQ14M7GrrssBoD0A3/ri9BkbJGWWeAkT473CtaJTUA1vFIIK4YiKlcXRKyQ==">
      <div class="form-label-group">
        <input type="text" name="build[title]" id="inputText" class="form-control" placeholder="Title" required autofocus>
      </div>
      <div class="form-label-group">
        <textarea type="textarea" name="build[description]" id="inputPassword" class="form-control" placeholder="Description" rows="4'" style="resize:none;" required></textarea>
      </div>
      <button class="item-content-btn" type="submit">Create</button>
    </form>
  </div>
</div>

app/views/builds/private_index.html.erb
<div class= "builds-wrapper">
  <h1><%=@user.name.capitalize%>'s Builds</h1>
  <div class="builds-content">
    <% @builds.each do |build|%>
      <a class="builds-card" style="background: <%=@colors.sample%>" href=<%=build_path(build.user,build)%>>
        <div class="builds-div"></div>
        <div class="builds-content">
          <%= content_tag(:span, build.title, class:"builds-title") %>
          <%= content_tag(:span, build.description,class:"builds-description") %>        <% if build.public %>
            <%= content_tag(:span, "public", class:"builds-author")%>
          <% else %>
            <%= content_tag(:span, "private", class:"builds-author")%>
          <%end%>
        </div>
      </a>
    <%end%>
  </div>
</div>

app/views/builds/show.html.erb
<div style="min-height: 83vh;" class="item-container">
  <div class="item-content">
    <div class="item-content-title">
      <%=@build.title%>
    </div>
    <div style="text-align: center;" class="item-content-description">
      <b><%=@owner.name %></b>
    </div>
    <div class="item-content-description">
      <%=@build.description %>
    </div>
    <% if @item.name %>
      <div class="item-content-description">
        <b><%=@item.name %></b>
      </div>
      <div class="item-content-description">
        Type: <%=@item.type %>
      </div>
      <div class="item-content-description">
        Price: $<%=sprintf('%.2f', @item.price_in_cents/100) rescue 0%>
      </div>
    <%end%>
    <div class="item-content-form">
      <%if @item.name %>
        <%=button_to "Add Item to Cart", add_to_cart_path(@item), class: "item-content-btn"%>
      <%end%>
      <%= button_to "Add Build to Cart", add_build_to_cart_path(@build), class: "item-content-btn"%>
      <% if @build.user_id == @user.id %>
        <%= button_to "Edit Build", edit_build_path(@build), {class: "item-content-btn", id: "secondary",method: :get} %>
        <% if @build.public %>
          <%= button_to "Unpublish", build_path(@owner, @build), {class: "item-content-btn ", id: "secondary",method: :post}%>
        <% else %>
          <%= button_to "Publish", build_path(@owner, @build), {class: "item-content-btn ",id: "secondary", method: :post}%>
        <%end%>
        <%=button_to "Delete", build_path(@owner, @build), {class: " item-content-btn ",id: "secondary",  method: :delete}%>
      <% end%>
    </div>
  </div>
  <div class="item-content-background"></div>
  <div class="item-index">
    <% @items.each do |item|%>
      <form action=#<%=item.id%> method="get">
        <button style="outline: none" class="item-card-btn " type="submit" name="it" value=<%=item.id%>>
          <%if @item.id==item.id %>
            <div type=submit id="item-card-select" class="item-card " style="width: 18rem;">
            <% else %>
              <div type=submit class="item-card" style="width: 18rem;">
              <%end%>
              <img src="<%=item.image_url%>" class="item-card-image">
              <div class="item-card-body">
                <div class="item-card-title">
                  <span id=<%=item.id%> class="item-reference"></span>
                  <%=item.name%></div>
                <div class="item-card-description">Type: <%=item.type%></div>
                <p class="item-card-description">
                  Price: $<%=sprintf('%.2f', item.price_in_cents/100) rescue 0%></p>
              </div>
            </div>
          </button>
        </form>
      <%end%>
    </div>
  </div>