config/routes.rb
Rails.application.routes.draw do
  get "/", to: "static#index", as: "root"

  get "register", to: "users#new", as: "new_user"
  post "register", to: "users#create"

  get "login", to: "sessions#index", as: "login"
  post "login", to: "sessions#login"
  get "logout", to: "sessions#logout"

  get "items", to: "items#index", as: "items"
  get "items/:id", to: "items#show", as: "item"
  post "items/:id/add_to_cart", to: "items#add_to_cart", as: "add_to_cart"
  delete "items/:id/remove_from_cart", to: "items#remove_from_cart", as: "remove_item_from_cart"
  post "items/:id/add_to_build", to: "items#add_to_build", as: "add_to_build"
  post "items/:build_id", to: "items#add_build_to_cart", as: "add_build_to_cart"
  post "items", to: "items#post"

  get "cart", to: "carts#show", as: "cart"
  post "cart/clear", to: "carts#delete", as: "clear_cart"

  get "users/:id/", to: "builds#private_index", as: "user"

  get "builds", to: "builds#index", as: "builds"

  get "users/:id/:build_id", to: "builds#show", as: "build"
  get "builds/new", to: "builds#new", as: "new_build"
  get "builds/:build_id/edit", to: "builds#edit", as: "edit_build"
  delete "builds/:build_id/:item_id", to: "builds#remove_item", as: "delete_item_from_build"

  patch "builds/:build_id", to: "builds#update", as: "update_build"
  post "builds", to: "builds#create"
  post "users/:id/:build_id", to: "builds#post"
  delete "users/:id/:build_id", to: "builds#delete"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  has_many :carts_items
  has_many :items, through: :carts_items

  def clear_cart
    carts_items.destroy_all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @items = user.cart.items

    @total = @items.sum(&:price_in_cents) rescue 0

    @user = user

    @item = Item.find(params[:it]) rescue Item.new
  end

  def delete
    user.cart.clear_cart
    redirect_to cart_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<%if @items.empty? %>
  <div class="empty-cart">
    <%= content_tag(:h1, "your cart is empty :(")%>
  </div>
<%else%>
  <div style="min-height: 83vh;" class="item-container">
    <div class="cart-content">
      <div class="cart-content-title">
        Total: $<%=sprintf('%.2f', @total/100)%>
      </div>
      <div style="text-align: center;" class="item-content-description">
        <b>Cart</b>
      </div>
      <%if @item.name %>
        <div class="item-content-description">
          <%=@item.description%>
        </div>
      <%end%>
      <div class="item-content-form">
        <% if @item.name%>
          <%= button_to "Remove Item", remove_item_from_cart_path(@item), id: "secondary",class: "item-content-btn", method: :delete%>
        <% end%>
        <%= button_to "Clear Cart", clear_cart_path,id: "secondary", class: "item-content-btn"%>
        <%= button_to "Buy NOW", clear_cart_path,  style: "height: 75px;", class: "item-content-btn"%>
      </div>
    </div>
    <div class="cart-content-background"></div>
    <div class="item-index">
      <% @items.each do |item|%>
        <form action=#<%=item.id%> method="get">
          <button style="outline: none" class="item-card-btn " type="submit" name="it" value=<%=item.id%>>
            <%if @item.id==item.id %>
              <div type=submit id="item-card-select" class="item-card " style="width: 18rem;">
              <% else %>
                <div type=submit class="item-card" style="width: 18rem;">
                <%end%>
                <img src="<%=item.image_url%>" class="item-card-image">
                <div class="item-card-body">
                  <div class="item-card-title">
                    <span id=<%=item.id%> class="item-reference"></span>
                    <%=item.name%></div>
                  <div class="item-card-description">Type: <%=item.type%></div>
                  <p class="item-card-description">
                    Price: $<%=sprintf('%.2f', item.price_in_cents/100) rescue 0%>
                  </p>
                </div>
              </div>
            </button>
          </form>
        <%end%>
      </div>
    </div>
  <%end%>