config/routes.rb
Rails.application.routes.draw do
  get "/", to: "static#index", as: "root"

  get "register", to: "users#new", as: "new_user"
  post "register", to: "users#create"

  get "login", to: "sessions#index", as: "login"
  post "login", to: "sessions#login"
  get "logout", to: "sessions#logout"

  get "items", to: "items#index", as: "items"
  get "items/:id", to: "items#show", as: "item"
  post "items/:id/add_to_cart", to: "items#add_to_cart", as: "add_to_cart"
  delete "items/:id/remove_from_cart", to: "items#remove_from_cart", as: "remove_item_from_cart"
  post "items/:id/add_to_build", to: "items#add_to_build", as: "add_to_build"
  post "items/:build_id", to: "items#add_build_to_cart", as: "add_build_to_cart"
  post "items", to: "items#post"

  get "cart", to: "carts#show", as: "cart"
  post "cart/clear", to: "carts#delete", as: "clear_cart"

  get "users/:id/", to: "builds#private_index", as: "user"

  get "builds", to: "builds#index", as: "builds"

  get "users/:id/:build_id", to: "builds#show", as: "build"
  get "builds/new", to: "builds#new", as: "new_build"
  get "builds/:build_id/edit", to: "builds#edit", as: "edit_build"
  delete "builds/:build_id/:item_id", to: "builds#remove_item", as: "delete_item_from_build"

  patch "builds/:build_id", to: "builds#update", as: "update_build"
  post "builds", to: "builds#create"
  post "users/:id/:build_id", to: "builds#post"
  delete "users/:id/:build_id", to: "builds#delete"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :carts_items
  has_many :carts, through: :carts_items

  has_many :builds_items
  has_many :items, through: :builds_items

  def self.create_deck(name, brand, price_in_cents, description, image_url, length, width, material, mounting_type)
    create(
      name: name, brand: brand, price_in_cents: price_in_cents, description: description, image_url: image_url,
      type: "Deck",
      deck_length: length,
      deck_width: width,
      deck_material: material,
      deck_mounting_type: mounting_type,
    )
  end

  def self.create_trucks(name, brand, price_in_cents, description, image_url, color, size_in_mm, standard_kingpin, axel_degree)
    create(
      name: name, brand: brand, price_in_cents: price_in_cents, description: description, image_url: image_url,
      type: "Truck",
      color: color,
      truck_size_in_mm: size_in_mm,
      truck_standard_kingpin?: standard_kingpin,
      truck_axel_degree: axel_degree,
    )
  end

  def self.create_wheels(name, brand, price_in_cents, description, image_url, color, durometer, size_in_mm, center_cut)
    create(
      name: name, brand: brand, price_in_cents: price_in_cents, description: description, image_url: image_url,
      type: "Wheel",
      color: color,
      wheel_size_in_mm: size_in_mm,
      wheel_center_cut?: center_cut,
      wheel_durometer: durometer,
    )
  end

  def self.create_bearings(name, brand, price_in_cents, description, image_url, open, abec)
    create(
      name: name, brand: brand, price_in_cents: price_in_cents, description: description, image_url: image_url,
      type: "Bearing",
      bearing_open?: open,
      bearing_abec?: abec,
    )
  end

  def self.create_grip_tape(name, brand, price_in_cents, description, image_url, color, length, width)
    create(
      name: name, brand: brand, price_in_cents: price_in_cents, description: description, image_url: image_url,
      type: "Griptape",
      griptape_length: length,
      griptape_width: width,
    )
  end

  def self.search(query)
    all.select { |item|
      item.type.downcase.include?(query.downcase) ||
      item.name.downcase.include?(query.downcase)
    }
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @user = user
    @items = Item.all

    @search = params[:search]
    if (@search)
      @items = Item.search(@search)
    else
      @search = ""
    end

    @item = Item.find(params[:it]) rescue Item.new
    @user_builds = user.builds
  end

  def post
    redirect_back fallback_location: items_path
  end

  def add_to_cart
    user.add_item_to_cart(item)
    redirect_to cart_path
  end

  def remove_from_cart
    user.cart.carts_items.destroy(user.cart.carts_items.find_by_item_id(params[:id]))
    redirect_to cart_path
  end

  def add_to_build
    build = Build.find(params[:build][:id])
    user.add_item_to_build(build, item)
    redirect_to build_path(user, build)
  end

  def add_build_to_cart
    build = Build.find(params[:build_id])
    build.items.each { |item|
      user.add_item_to_cart(item)
    }
    redirect_to cart_path
  end

  private

  def item
    Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<div class="item-container">
  <div class="item-content">
    <div class="item-content-title">
      <% if @item.name %>
        <%= @item.name %>
      <%else%>
        Select an item.<br>
      <%end%>
    </div>
    <%=form_tag items_path, method: :get, class: 'item-search-bar' do %>
      <%= text_field_tag :search, @search, placeholder: "search by name/type", class: "form-control", style: "text-align: center;"%>
    <%end%>
    <%if @item.name %>
      <div class="item-content-description">
        <b><%=@item.brand%></b>
      </div>
      <div class="item-content-description">
        <%=@item.description%>
      </div>
      <div class="item-content-description">
        <%=@item.type%>
      </div>
      <div class="item-content-description">
        $<%=sprintf('%.2f', @item.price_in_cents/100)%>
      </div>
      <div class="item-content-form">
        <%=button_to "Add to Cart", add_to_cart_path(@item), class: "item-content-btn"%>
        <% if @user_builds.empty? %>
          <%=button_to "Create Build", new_build_path, method: :get, class: "item-content-btn"%>
        <% else %>
          <%= form_tag add_to_build_path(@item) do %>
            <%= submit_tag :"Add to Build",class: "item-content-btn"%><br>
            <%= collection_select(:build, :id, @user_builds, :id, :title, class: "item-content-selector") %>
          <%end%>
        <%end %>
      </div>
    <%end%>
  </div>
  <div class="item-content-background"></div>
  <div class="item-index">
    <% @items.each do |item|%>
      <form action=#<%=item.id%> method="get">
        <button style="outline: none" class="item-card-btn " type="submit" name="it" value=<%=item.id%>>
          <input type="hidden" name="search" value=<%=@search%>>
          <%if @item.id==item.id %>
            <div id="item-card-select" class="item-card " style="width: 18rem;">
            <% else %>
              <div class="item-card" style="width: 18rem;">
              <%end%>
              <img src="<%=item.image_url%>" class="item-card-image">
              <div class="item-card-body">
                <div class="item-card-title">
                  <span id=<%=item.id%> class="item-reference"></span>
                  <%=item.name%></div>
                <div class="item-card-description">Type: <%=item.type%></div>
                <p class="item-card-description">
                  Price: $<%=sprintf('%.2f', item.price_in_cents/100) rescue 0%></p>
              </div>
            </div>
          </button>
        </form>
      <%end%>
    </div>
  </div>

app/views/items/show.html.erb
Name: <%=  @item.name %></br>
Brand: <%=  @item.brand %> </br>
Type: <%=  @item.type%></br>
Price: <%=  @item.price_in_cents %></br>
Description: <%=  @item.description %></br>
<img class="item_image" src=<%=@item.image_url%>>