config/routes.rb
Rails.application.routes.draw do
  get "/", to: "static#index", as: "root"

  get "register", to: "users#new", as: "new_user"
  post "register", to: "users#create"

  get "login", to: "sessions#index", as: "login"
  post "login", to: "sessions#login"
  get "logout", to: "sessions#logout"

  get "items", to: "items#index", as: "items"
  get "items/:id", to: "items#show", as: "item"
  post "items/:id/add_to_cart", to: "items#add_to_cart", as: "add_to_cart"
  delete "items/:id/remove_from_cart", to: "items#remove_from_cart", as: "remove_item_from_cart"
  post "items/:id/add_to_build", to: "items#add_to_build", as: "add_to_build"
  post "items/:build_id", to: "items#add_build_to_cart", as: "add_build_to_cart"
  post "items", to: "items#post"

  get "cart", to: "carts#show", as: "cart"
  post "cart/clear", to: "carts#delete", as: "clear_cart"

  get "users/:id/", to: "builds#private_index", as: "user"

  get "builds", to: "builds#index", as: "builds"

  get "users/:id/:build_id", to: "builds#show", as: "build"
  get "builds/new", to: "builds#new", as: "new_build"
  get "builds/:build_id/edit", to: "builds#edit", as: "edit_build"
  delete "builds/:build_id/:item_id", to: "builds#remove_item", as: "delete_item_from_build"

  patch "builds/:build_id", to: "builds#update", as: "update_build"
  post "builds", to: "builds#create"
  post "users/:id/:build_id", to: "builds#post"
  delete "users/:id/:build_id", to: "builds#delete"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bearing.rb
class Bearing < Item
end

app/models/build.rb
class Build < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true

  has_many :builds_items
  has_many :items, through: :builds_items

  belongs_to :user

  def publish
    self.public = true
    self.save
  end

  def unpublish
    self.public = false
    self.save
  end
end

app/models/builds_item.rb
class BuildsItem < ApplicationRecord
  belongs_to :item
  belongs_to :build
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  has_many :carts_items
  has_many :items, through: :carts_items

  def clear_cart
    carts_items.destroy_all
  end
end

app/models/carts_item.rb
class CartsItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/deck.rb
class Deck < Item
end

app/models/griptape.rb
class Griptape < Item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :carts_items
  has_many :carts, through: :carts_items

  has_many :builds_items
  has_many :items, through: :builds_items

  def self.create_deck(name, brand, price_in_cents, description, image_url, length, width, material, mounting_type)
    create(
      name: name, brand: brand, price_in_cents: price_in_cents, description: description, image_url: image_url,
      type: "Deck",
      deck_length: length,
      deck_width: width,
      deck_material: material,
      deck_mounting_type: mounting_type,
    )
  end

  def self.create_trucks(name, brand, price_in_cents, description, image_url, color, size_in_mm, standard_kingpin, axel_degree)
    create(
      name: name, brand: brand, price_in_cents: price_in_cents, description: description, image_url: image_url,
      type: "Truck",
      color: color,
      truck_size_in_mm: size_in_mm,
      truck_standard_kingpin?: standard_kingpin,
      truck_axel_degree: axel_degree,
    )
  end

  def self.create_wheels(name, brand, price_in_cents, description, image_url, color, durometer, size_in_mm, center_cut)
    create(
      name: name, brand: brand, price_in_cents: price_in_cents, description: description, image_url: image_url,
      type: "Wheel",
      color: color,
      wheel_size_in_mm: size_in_mm,
      wheel_center_cut?: center_cut,
      wheel_durometer: durometer,
    )
  end

  def self.create_bearings(name, brand, price_in_cents, description, image_url, open, abec)
    create(
      name: name, brand: brand, price_in_cents: price_in_cents, description: description, image_url: image_url,
      type: "Bearing",
      bearing_open?: open,
      bearing_abec?: abec,
    )
  end

  def self.create_grip_tape(name, brand, price_in_cents, description, image_url, color, length, width)
    create(
      name: name, brand: brand, price_in_cents: price_in_cents, description: description, image_url: image_url,
      type: "Griptape",
      griptape_length: length,
      griptape_width: width,
    )
  end

  def self.search(query)
    all.select { |item|
      item.type.downcase.include?(query.downcase) ||
      item.name.downcase.include?(query.downcase)
    }
  end
end

app/models/truck.rb
class Truck < Item
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :email, presence: true
  validates :email, uniqueness: true

  validates :name, presence: true

  has_one :cart
  has_many :items, through: :carts
  has_many :builds

  def cart
    user_cart = super
    unless (user_cart)
      user_cart = Cart.create!(user_id: self.id)
    end
    user_cart
  end

  def add_item_to_cart(item)
    CartsItem.create!(cart_id: cart.id, item_id: item.id)
  end

  def add_item_to_build(build, item)
    BuildsItem.create!(build_id: build.id, item_id: item.id)
  end
end

app/models/wheel.rb
class Wheel < Item
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @items = user.cart.items

    @total = @items.sum(&:price_in_cents) rescue 0

    @user = user

    @item = Item.find(params[:it]) rescue Item.new
  end

  def delete
    user.cart.clear_cart
    redirect_to cart_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SP3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap" rel="stylesheet">
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SP3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="session-wrapper">
      <div class="session-navbar">
        <a class="nav-banner" href="/">SP3</a>
        <a class="nav-action" href=<%= items_path%>>All Items</a>
        <a class="nav-action" href=<%=builds_path%>>Public Builds</a>
        <a class="nav-action" href=<%= new_build_path%>>Create Build</a>
        <a class="nav-action" href=<%=cart_path%>>View Cart</a>
        <a class="nav-action" href="/logout">Logout</a>
      </div>
      <div>
      </div>
      <div class="session-main">
        <%= yield %>
      </div>
      <div class="session-footer">
        &copy; 2019 - SPB3
      </div>
    </div>
  </body>
</html>